# Generated by Django 3.2.3 on 2021-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('RutColab', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut Colaborador')),
                ('Fotografia', models.ImageField(upload_to='img', verbose_name='Foto Del Colaborador')),
                ('Nombre', models.CharField(max_length=70, verbose_name='Nombre del Colaborador')),
                ('Fono', models.IntegerField(verbose_name='Numbero de Telefono')),
                ('Direcc', models.CharField(max_length=30, verbose_name='Direccion')),
                ('Email', models.CharField(max_length=70, verbose_name='Correo del colaborador')),
                ('Pais', models.CharField(max_length=70, verbose_name='Pais')),
                ('Contra', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
        ),
    ]
