# Generated by Django 3.2.3 on 2021-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='Fotografia',
            field=models.ImageField(upload_to='img/', verbose_name='Foto Del Colaborador'),
        ),
    ]
