# Generated by Django 3.2.3 on 2021-07-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_colaborador_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='Fotografia',
            field=models.ImageField(upload_to='img/', verbose_name='Foto del colaborador'),
        ),
    ]
